"""add interval to action

Revision ID: 1224dcf0bea5
Revises: c88c7e5e36dd
Create Date: 2024-11-27 15:35:49.336626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1224dcf0bea5'
down_revision = 'c88c7e5e36dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('interval', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('interval')
        batch_op.drop_column('reward')

    # ### end Alembic commands ###
