"""add global env

Revision ID: c88c7e5e36dd
Revises: bd9676c5eea6
Create Date: 2024-11-27 13:52:35.765944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c88c7e5e36dd'
down_revision = 'bd9676c5eea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('observation', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'interval', name='_pair_interval_uc')
    )
    op.drop_table('action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('action', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('observation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='action_pkey')
    )
    op.drop_table('global_environments')
    op.drop_table('actions')
    # ### end Alembic commands ###
